name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7232c6024da9ffb1bceabd227f15483461c77e78a6a538680159c1183c25f2b0"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
