name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e9c861fd9da969821a898f8fd7c717236509c33ccbab8f4d09f14c8fee508bb"

[versions]
minecraft = "1.20.1"
quilt = "0.27.1-beta.1"
