name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f4c17cd8a6f10cb5dc83d3959a332579f585d019718c299860dcc82c2b3967f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
