name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df95ed7df9555351606c7ab6f5a4445274ae47db517610fc125e5ea00c591d10"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
