name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39e328d11ae4050a4caafbf225dd2935a75948fda819cc473f32944a5f0b247c"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
