name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb523b24e75f357dd0f4a333b105272057c738e3d7f6044c26977554fde7a6f3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
