name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "340d6897f5da2715f6b399df964c8e502e5dccb17e42d66f3d462201d301fdf3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
