name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc53d60948dda085189a4b8c4bfcc5f5d2d8259054fcdc742103c9d2cd7b61dc"

[versions]
minecraft = "1.20.1"
quilt = "0.27.1-beta.1"
