name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "572c79e8204602c870b8ba487757753d4c4d4baaeb246152ba99bf369989dc6a"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
