name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1f4cdda33a51ce2d6fead9f28b6037be7f62ce3b8fc0f0702eb05a4309cd502"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
