name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26c9177e534a209d5e30b8e28828eeb58208c69bfeecd092e3a7803c23ffeb35"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
