name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcf6da24eb07feb3a3072fec4c2f7c3883b9a64fb2c2d4afdf5ce3fa25d5c870"

[versions]
minecraft = "1.20.1"
quilt = "0.27.1-beta.1"
