name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22d02715e3b348252d4eca99418d72a5f1c4ef055054b775e7c4dde2bcd79ad7"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
