name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deffc7091056fa8e967d6a64795845b6d31ce693b58cbd20a7bb84af89c8046b"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
