name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b7ca4be503de4e636251b56495572a8499742327a4c9864cdeedd43bb38eb09"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
