name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c9803454b9f9df35e5123daafe7dcc50aa1c4fab7150c02f2d3ac0e105f5943"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
