name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a80fd0547a4d20bb0e57faccfea1505cbd8e776b7befcbef32c4a375fa1ce6fb"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
