name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2cb5d13d1befc4448cf2672e5412cf46e093b1c4cbc26c5aae47b4214e6ba61"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
