name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af6707729fc38a187a65e4d19daad67d509a8edb0b1ef828ae41dada50edb092"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
