name = "CDRP Non Event Chicanery"
author = "Ski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6fb432e3eef555fd9d4ee613f85bb72270d8542c7ae89c594125e47010d2b21"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
